name: Build Kernel

on: [push]

defaults:
  run:
    working-directory: ./linux

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make sure there are no changes
        run: pwd && git pull
      - name: Make Mr. Proper (clean)
        run: make mrproper
      - name: Setup defconfig
        run: make defconfig
      - name: Build
        run: make -j $(nproc)
      - name: Build modules
        run: make -j $(nproc) modules
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            arch/x86_64/boot/*
            System.map
            drivers/acpi/*.ko
            net/ipv6/netfilter/*.ko
            net/ipv4/netfilter/*.ko
            net/netfilter/*.ko
            fs/efivars/*.ko
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}