name: Build Kernel

on:
  push:
    tags:
      - '*.*.*'

defaults:
  run:
    working-directory: ./linux

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v2
      - name: Show directory
        run: ls
      - name: Make sure upstream is good
        run: git pull
      - name: Get needed build dependencies
        run: sudo apt install build-essential libelf-dev -y
      - name: Make Mr. Proper (clean any build artifacts)
        run: make mrproper
      - name: Setup default x86 settings
        run: make defconfig
      - name: Build
        run: echo "$(nproc) processors" && make -j $(nproc)
      - name: Build modules
        run: make -j $(nproc) modules
      - name: Show directory
        run: ls
      - name: Release output files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/arch/x86/boot/*
            linux/System.map
            linux/drivers/acpi/*.ko
            linux/net/ipv6/netfilter/*.ko
            linux/net/ipv4/netfilter/*.ko
            linux/net/netfilter/*.ko
            linux/fs/efivars/*.ko
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}