name: Build Kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get build requirements
        run: sudo apt install build-essential -y
      - name: Get source
        run: git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
      - name: Get existing config
        run: cp /boot/config-$(uname -r) .config
      - name: Accept any config changes
        run: yes '' | make oldconfig
      - name: Clean
        run: make clean
      - name: Build
        run: make -j $(getconf _NPROCESSORS_ONLN) deb-pkg LOCALVERSION=-custom && cd ../
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}